import openpyxl


wb = openpyxl.load_workbook('outV.xlsx')
ws = wb.active

# add 9 rows of zeros after every 9 lines of data. generated by ChatGPT.
for i in range(ws.max_row, 0, -9):
    ws.insert_rows(i, 9)
    for j in range(i, i + 9):
        for k in range(1, ws.max_column + 1):
            ws.cell(row=j, column=k).value = 0

wb.save('outV_treated.xlsx')
